/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface ConfigResponse {
    claim_msg_plaintext: string;
    owner?: string | null;
    [k: string]: unknown;
  }
  export type ExecuteMsg = {
    claim: {
      amount: Uint128;
      eth_pubkey: string;
      eth_sig: string;
      proof: string[];
      [k: string]: unknown;
    };
  } | {
    claw_back: {
      recipient: string;
      [k: string]: unknown;
    };
  } | {
    pause: {
      [k: string]: unknown;
    };
  } | {
    resume: {
      [k: string]: unknown;
    };
  };
  export type Uint128 = string;
  export interface InstantiateMsg {
    claim_msg_plaintext: string;
    merkle_root: string;
    owner?: string | null;
    total_amount?: Uint128 | null;
    [k: string]: unknown;
  }
  export interface IsClaimedResponse {
    is_claimed: boolean;
    [k: string]: unknown;
  }
  export interface MerkleRootResponse {
    merkle_root: string;
    total_amount: Uint128;
    [k: string]: unknown;
  }
  export type QueryMsg = {
    config: {
      [k: string]: unknown;
    };
  } | {
    merkle_root: {
      [k: string]: unknown;
    };
  } | {
    is_claimed: {
      address: string;
      [k: string]: unknown;
    };
  } | {
    total_claimed: {
      [k: string]: unknown;
    };
  };