export const PINATA_ENDPOINT_URL = process.env.NEXT_PUBLIC_PINATA_ENDPOINT_URL
export const FAUCET_ENDPOINT_URL = process.env.NEXT_PUBLIC_FAUCET_ENDPOINT_URL
export const NETWORK = process.env.NEXT_PUBLIC_NETWORK
export const API_URL = process.env.NEXT_PUBLIC_API_URL
export const STARGAZE_URL = process.env.NEXT_PUBLIC_STARGAZE_WEBSITE_URL
export const BLOCK_EXPLORER_URL = process.env.NEXT_PUBLIC_BLOCK_EXPLORER_URL
export const WEBSITE_URL = process.env.NEXT_PUBLIC_DASH_URL
export const HEADSTASH_CONTRACT_MAINNET = process.env.NEX_PUBLIC_HEADSTASH_CONTRACT_MAINNET
export const HEADSTASH_CONTRACT_TESTNET = process.env.NEX_PUBLIC_HEADSTASH_CONTRACT_TESTNET


// export const SYNC_COLLECTIONS_API_URL = process.env.NEXT_PUBLIC_SYNC_COLLECTIONS_API_URL
