import Head from 'next/head';
import NextLink from 'next/link';
import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { Product, Dependency } from '../components';
import { dependencies, products } from '../config';
import { ArrowForwardIcon } from '@chakra-ui/icons';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Community Widget Dashboard - Terp Network</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
          The Headstash Dashboard
        </Heading>
        <Heading
          as="h1"
          fontWeight="bold"
          fontSize={{ base: '2xl', sm: '3xl', md: '4xl' }}
        >
         
          <Text
            as="span"
            color={useColorModeValue('primary.500', 'primary.200')}
          >
           Connect yo' Metamask to view yo' tokens!
          </Text>
        </Heading>
      </Box>
      <Stack direction="row" justifyContent="center" my={12} spacing={4}>
        <NextLink href="w/delegate">
          <Button colorScheme="blue" rightIcon={<ArrowForwardIcon />}>
           Delegate yo' TERP
          </Button>
        </NextLink>
       
      </Stack>
    
      <Box mb={3}>
        <Divider />
      </Box>
      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
        <Text>Built with</Text>
        <Link
          href="https://cosmology.tech/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
      </Stack>
    </Container>
  );
}
